sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=docs-neutron
    - VERSION=1.0.0
    # The following variables are set as GitHub repository properties
    # REGISTRY_USER=<user name of docker registry>
    # REGISTRY_PASS=<password of docker registry>


script:
  - docker build --tag "$IMAGE_NAME" .
  - docker images
  - docker tag "$IMAGE_NAME" "$REGISTRY_USER/$IMAGE_NAME":"$VERSION"

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
